export const SET_DESTINATIONS = "SET_DESTINATIONS";
export const SET_OUTPUT = "SET_OUTPUT";
export const SET_OUTPUT_INFO = "SET_OUTPUT_INFO";
export const SET_SUGGESTION = "SET_SUGGESTION";
export const SET_TEXT_OBJECT = "SET_TEXT_OBJECT";
export const SET_TEXT_OBJECT_VF = "SET_TEXT_OBJECT_VF";
export const SET_TEXT_OBJECT_VOA = "SET_TEXT_OBJECT_VOA";
export const SET_TEXT_OBJECT_ETA = "SET_TEXT_OBJECT_ETA";
export const SET_TEXT_OBJECT_VR = "SET_TEXT_OBJECT_VR";

// Input Handlers
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const UPDATE_CHECK = "UPDATE_CHECK";

export const SEARCH_DEST = "SEARCH_DEST";
